### ISSUE TITLE
ldpjs.mybluemix.net out of order

### ISSUE THREAD

**Issue by akuckartz** [spadgett/LDPjs#2]
```
404 Not Found: Requested route ('ldpjs.mybluemix.net') does not exist.
```

**Comment by BigBlueHat** [comment]
FWIW the http://ldpjs.mybluemix.net/ site is working now and the http://ldp-speicher.rhcloud.com/ is not...life and time on the Web, I guess. 😜 

Propose closing #2 and #3 as `wontfix` (because not currently broken). 😁

**Comment by akuckartz** [comment]
Fixed.
